

  # num_bins: 1500
  
  # percentage of bin exposed to the model expressed in decimal 
  # percentile_bins: 0.1

  # model_options:
  #     num_classes: 1
  #     num_epochs: 100
  #     batch_size: 64
  #     learning_rate: 0.001
  #     test_size: 0.2
  #     random_state: 3
  #     input_size: 1 
  #     sequence_length: 2 # the window it trains with can be selected
  #     hidden_size: 128
  #     num_layers: 2